from __future__ import annotations

from collections import Counter
from datetime import datetime, UTC
from pathlib import Path
import json
from typing import Any

from .scanner import Finding

SEVERITY_RANK = {
    "critical": 4,
    "high": 3,
    "medium": 2,
    "low": 1,
}


def _fingerprint(f: Finding) -> str:
    return f"{f.id}|{f.title}|{f.severity}|{f.confidence}|{f.evidence}|{f.fix}"


def save_baseline(path: Path, findings: list[Finding], workspace: Path) -> None:
    payload = {
        "created_at": datetime.now(UTC).isoformat(),
        "workspace": str(workspace.resolve()),
        "findings": [f.as_dict() for f in findings],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def load_baseline(path: Path) -> dict[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("invalid baseline format")
    return raw


def compare_findings(current: list[Finding], previous_payload: dict[str, Any]) -> dict[str, Any]:
    prev_raw = previous_payload.get("findings", [])
    prev_findings = [Finding(**f) for f in prev_raw if isinstance(f, dict)]

    prev_map = {_fingerprint(f): f for f in prev_findings}
    curr_map = {_fingerprint(f): f for f in current}

    added = [curr_map[k].as_dict() for k in sorted(curr_map.keys() - prev_map.keys())]
    removed = [prev_map[k].as_dict() for k in sorted(prev_map.keys() - curr_map.keys())]

    current_counter = Counter(f.severity for f in current)
    previous_counter = Counter(f.severity for f in prev_findings)

    return {
        "summary": {
            "current_total": len(current),
            "previous_total": len(prev_findings),
            "added": len(added),
            "removed": len(removed),
            "current_by_severity": dict(current_counter),
            "previous_by_severity": dict(previous_counter),
        },
        "added": added,
        "removed": removed,
    }


def should_fail_on_added_severity(diff: dict[str, Any], min_severity: str | None) -> bool:
    if not min_severity:
        return False
    threshold = SEVERITY_RANK.get(min_severity.lower())
    if threshold is None:
        return False

    for item in diff.get("added", []):
        sev = str(item.get("severity", "")).lower()
        if SEVERITY_RANK.get(sev, 0) >= threshold:
            return True
    return False


def render_pr_template(findings: list[Finding], workspace: Path) -> str:
    sev_order = ["critical", "high", "medium", "low"]
    counts = Counter(f.severity for f in findings)

    lines = [
        "## Summary",
        f"Security scan for `{workspace.resolve()}`.",
        "",
        "## Risk snapshot",
        "| Severity | Count |",
        "|---|---:|",
    ]

    for sev in sev_order:
        if counts.get(sev, 0):
            lines.append(f"| {sev} | {counts[sev]} |")

    if not findings:
        lines.append("\nNo findings. ✅")
        return "\n".join(lines)

    lines.extend([
        "",
        "## Findings by rule",
    ])

    grouped: dict[str, list[Finding]] = {}
    for f in findings:
        grouped.setdefault(f.id, []).append(f)

    for rid, items in sorted(grouped.items()):
        top = items[0]
        lines.extend([
            f"### {rid} — {top.title}",
            f"- Severity: **{top.severity}**",
            f"- Suggested fix: {top.fix}",
            f"- Instances: {len(items)}",
        ])

    lines.extend([
        "",
        "## Validation",
        "- [ ] `python -m unittest discover -s projects/clawgarda/tests -v`",
        "- [ ] `clawgarda scan --workspace <target> --format table`",
        "",
        "## Notes",
        "- This PR template is generated by `clawgarda report --pr-template`.",
    ])

    return "\n".join(lines)


def render_markdown_report(findings: list[Finding], workspace: Path) -> str:
    if not findings:
        return "# ClawGarda Report\n\nNo findings. ✅\n"

    sev_order = ["critical", "high", "medium", "low"]
    counts = Counter(f.severity for f in findings)
    lines = [
        "# ClawGarda Report",
        "",
        f"- Workspace: `{workspace.resolve()}`",
        f"- Total findings: **{len(findings)}**",
        "- Severity summary: " + ", ".join(
            f"{s}: {counts.get(s, 0)}" for s in sev_order if counts.get(s, 0)
        ),
        "",
        "## Findings",
        "",
    ]

    for idx, f in enumerate(findings, start=1):
        lines.extend(
            [
                f"### {idx}. [{f.severity.upper()}] {f.id} — {f.title}",
                f"- Evidence: {f.evidence}",
                f"- Fix: {f.fix}",
                "",
            ]
        )

    return "\n".join(lines)
